<?php

// create block for map
function calculate_drive_time_block_info() {
  $blocks['calculate_drive_time'] = array(
    'info' => t('Calculate Drive Time Block'),
  );
  return $blocks;
}

// call map in the created block
function calculate_drive_time_block_view($delta = '') {
  $blocks = array();
  switch ($delta) {
    case 'calculate_drive_time':
      $blocks['content'] = '
        <div class="widget-header"></div>
        <div class="drive-time-container">
          <h3 class="widget-title">Calculate Your Drive Time</h3>
          <div class="origin-container">
              <input id="origin-field" type="text" autocomplete="off" name="destination" placeholder="Destination">
          </div>
          <div class="calculate-container">
             <button class="calculate-button">Calculate</button>
          </div>

          <div class="result-container">
              <input type="text" id="result-field" autocomplete="off" name="result" placeholder="Result">
          </div>

          <div class="result-jquery-container">
            <p id="result-jquery-field">Placeholder</p>
          </div>
        </div>
      ';
    break;
  }
  return $blocks;
}

// create admin page
function calculate_drive_time_menu() {
  $items['admin/config/development/calculate_drive_time'] = array(
    'title' => 'Calculate Drive Time',
    'description' => 'Calculate drive time settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculate_drive_time_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

// create form for getting custom selector
function calculate_drive_time_form($form, &$form_state) {
  $form['calculate_drive_time_address_selector'] = array(
    '#type' => 'textarea',
    '#title' => t('jQuery address selector'),
    '#default_value' => variable_get('calculate_drive_time_address_selector', '#address'),
    '#description' => t('Retreive the base address using jQuery selector.'),
    '#required' => TRUE,
  );
  $form['use_address_field'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use Address module field value'),
    '#default_value' => variable_get('use_address_field'),
    '#description' => t('Checking this will cause the module to use the value
    of an address field on the node the block exists on instead of the 
    selector'),
  );
  // runs on submit function
  $form['#submit'][] = 'on_submit_action';
  return system_settings_form($form);
}
// on submit function
function on_submit_action() {
  // place any code here in future
}

function calculate_drive_time_page_build(&$page) {
  $address_module_status = db_query("SELECT name,status FROM system WHERE name='addressfield';");
  $node = menu_get_object();
  if (isset($node)) {
    $nid = $node->nid;
  }

  $use_address_module_checked = variable_get('use_address_field');

  if ($use_address_module_checked = 1) {
    if ($address_module_status = 1) {
      if (isset($nid)) {
        $get_this_nodes_address_field_values = db_query("SELECT 
          entity_id,
          field_address_thoroughfare,
          field_address_postal_code,
          field_address_dependent_locality,
          field_address_locality,
          field_address_administrative_area
          FROM 
          field_data_field_address
          WHERE 
          (entity_id = $nid)")->fetchAssoc();

        unset($get_this_nodes_address_field_values['entity_id']);
        $starting_address = implode(" ", $get_this_nodes_address_field_values);
      }
    } else {
      drupal_set_message(t('An error occured and we couldnt detect the Address module. Is the Address module turned on?'), 'error');
    }
  } else {
    $address_selector = variable_get('calculate_drive_time_address_selector');
    $starting_address = '"jQuery("' . $address_selector . '").text()"';
  }
  
  $page['content']['disclaimer'] = array(
    '#markup' => t('
      <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
      <script type="text/javascript" charset="utf-8" async defer>
        var startingAddress = "' . $starting_address . '";
      </script>
      '),
    '#weight' => -10,
  );
}

